# Generated by Django 5.1.1 on 2024-09-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Titre",
                    models.CharField(max_length=100, verbose_name="Titre de l'article"),
                ),
                (
                    "Statut",
                    models.CharField(
                        choices=[("presse", "Presse"), ("actualité", "Actualité")],
                        max_length=15,
                        verbose_name="Catégorie de l'article",
                    ),
                ),
                (
                    "Image",
                    models.ImageField(
                        default="default/DOUALAIR.png",
                        upload_to="article/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "Description",
                    models.TextField(verbose_name="Description de l'article"),
                ),
                ("date_publiee", models.DateField(auto_now_add=True)),
                ("date_mise_a_jour", models.DateField(auto_now=True)),
            ],
        ),
    ]
