# Generated by Django 5.1.1 on 2024-09-30 15:05

import django.core.validators
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Candidat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Nom", models.CharField(max_length=150, verbose_name="Nom")),
                (
                    "Prenom",
                    models.CharField(blank=True, max_length=150, verbose_name="Prenom"),
                ),
                (
                    "House",
                    models.CharField(max_length=150, verbose_name="Lieu de résidence"),
                ),
                (
                    "Phone_number",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Le numéro de téléphone doit être au format : '+999999999'. Le numéro de téléphone doit contenir entre 9 et 15 chiffres.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                        verbose_name="Numéro de téléphone",
                    ),
                ),
                (
                    "Email",
                    models.EmailField(
                        max_length=250, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "Profession",
                    models.CharField(max_length=100, verbose_name="Profession"),
                ),
                (
                    "CV",
                    models.FileField(
                        upload_to="cvs/",
                        validators=[home.models.validate_cv_file_extension],
                        verbose_name="Curriculum Vitae",
                    ),
                ),
                ("date_publiee", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Nom", models.CharField(max_length=200, verbose_name="Nom")),
                (
                    "Lieu",
                    models.CharField(max_length=150, verbose_name="Lieu de travail"),
                ),
                (
                    "Contrat",
                    models.CharField(
                        choices=[
                            ("CDD", "Contrat à durée déterminée"),
                            ("CDI", "Contrat à durée indéterminée"),
                            ("Freelance", "Freelance"),
                        ],
                        max_length=15,
                        verbose_name="Type de contrat",
                    ),
                ),
                (
                    "Nombre",
                    models.PositiveIntegerField(verbose_name="Nombre de postes"),
                ),
                ("Dateline", models.DateField()),
                ("date_publiee", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Nom",
                    models.CharField(max_length=100, verbose_name="Nom du Service"),
                ),
                (
                    "Image",
                    models.ImageField(
                        default="default/DOUALAIR.png",
                        upload_to="services/",
                        verbose_name="Représentation du Service",
                    ),
                ),
                (
                    "Description",
                    models.TextField(verbose_name="Description du Service"),
                ),
                (
                    "date_publiee",
                    models.DateField(auto_now_add=True, verbose_name="Date"),
                ),
                ("date_mise_a_jour", models.DateField(auto_now=True)),
            ],
        ),
    ]
